-------------------------------------------Night Allowance Query Start ----------------------------------------------------
SELECT
NAME, DESIGNATION, DEPARTMENT, SECTION_NAME, ATTEND_DATE , JOIN_DT, DD, EMP_ID,
DEPT_GROUP, DEPT_CODE, DESIG_CODE, DESIG_GROUP,
(CASE 
WHEN DESIG_GROUP ='OF' THEN EMP_AC_NO
WHEN DESIG_GROUP ='FW' THEN MOBILE_AC_NO
WHEN DESIG_GROUP ='OS' THEN MOBILE_AC_NO
ELSE NULL END) as ACCOUNT_NO,
(CASE 
WHEN EMP_AC_NO IS NOT NULL AND BANK_SAL_FLAG IS NOT NULL 
    OR MOBILE_AC_NO IS NOT NULL AND MOBILE_BANK_SAL_FLAG IS NOT NULL THEN
    NVL(NIGHT_ALL, 0)
ELSE 0
END) as NET_PAYABLE_BANK,
(CASE
WHEN EMP_AC_NO IS NULL AND BANK_SAL_FLAG IS NULL AND MOBILE_AC_NO IS NULL AND MOBILE_BANK_SAL_FLAG IS NULL THEN
    NVL(NIGHT_ALL, 0)
ELSE 0
END) as NET_PAYABLE_CASH

FROM (SELECT 
(SELECT ' '||O.DESIG_DESC FROM DESIGNATION O WHERE O.DEPT_GROUP = X.DEPT_GROUP AND O.DEPT_CODE  = X.DEPT_CODE AND O.DESIG_CODE = X.DESIG_CODE) as DESIGNATION,
(SELECT ' '||O.DEPT_GROUP_NAME FROM DEPT_GROUP O WHERE O.DEPT_GROUP_CODE = X.DEPT_GROUP) as DEPARTMENT,
(SELECT ' '||O.DEPT_DESC FROM DEPT O WHERE O.DEPT_GROUP = X.DEPT_GROUP AND O.DEPT_CODE  = X.DEPT_CODE) as SECTION_NAME,
ATTEND_DATE , DD, EMP_ID, NAME, BANK_SAL_FLAG,EMP_AC_NO,EMP_AC_DATE,MOBILE_BANK_SAL_FLAG,MOBILE_AC_NO,
MOBILE_AC_DATE, DEPT_GROUP, DEPT_CODE, DESIG_CODE, DESIG_GROUP, JOIN_DT,
(SELECT NVL(O.NIGHT_ALL,0) FROM HR_TNOFF_ALLOWANCE O
WHERE O.DEPT_GROUP  = X.DEPT_GROUP 
AND O.DEPT_CODE   =  X.DEPT_CODE  
AND O.DESIG_CODE  = X.DESIG_CODE 
AND O.EFFECTIVE_DATE  = (SELECT MAX(EFFECTIVE_DATE) 
                     FROM HR_TNOFF_ALLOWANCE 
                     WHERE DEPT_GROUP = X.DEPT_GROUP AND
                     DEPT_CODE        = X.DEPT_CODE  AND
                     DESIG_CODE      = X.DESIG_CODE AND
                     EFFECTIVE_DATE  <= TO_DATE(:P_MNYR,'MM/YYYY'))) NIGHT_ALL
FROM (SELECT JOIN_DT,BANK_SAL_FLAG,EMP_AC_NO,EMP_AC_DATE,MOBILE_BANK_SAL_FLAG,MOBILE_AC_NO,MOBILE_AC_DATE,ATTEND_DATE ,
DD,EMP_ID,NAME,IN_TIME,OUT_TIME,BASIC_SALARY,DEPT_GROUP,DEPT_CODE,DESIG_CODE,DESIG_GROUP,SALARY_TYPE
FROM
(SELECT DISTINCT B.JOIN_DT,B.BANK_SAL_FLAG,B.EMP_AC_NO,B.EMP_AC_DATE,B.MOBILE_BANK_SAL_FLAG,B.MOBILE_AC_NO,B.MOBILE_AC_DATE, A.ATTEND_DATE ,
TO_CHAR(A.ATTEND_DATE,'DY') DD,A.EMP_ID,B.NAME,TO_CHAR(A.IN_TIME,'HH12:MI AM') IN_TIME,TO_CHAR(A.OUT_TIME,'HH12:MI PM') OUT_TIME,
B.BASIC_SALARY,B.DEPT_GROUP,B.DEPT_CODE,B.DESIG_CODE,S.DESIG_GROUP,B.SALARY_TYPE
FROM DAILY_ATTENDANCE A, EMP B, DESIGNATION S
WHERE 
A.COMPANY_CODE                                   =B.COMPANY_CODE     AND
A.COMPANY_BRANCH_CODE                            =B.COMPANY_BRANCH_CODE    AND
A.EMP_ID                                         =B.EMP_ID    AND
B.DEPT_GROUP                                     = S.DEPT_GROUP  AND
B.DEPT_CODE                                      = S.DEPT_CODE  AND
B.DESIG_CODE                                     = S.DESIG_CODE AND
A.ATTEND_DATE != A.OUT_DATE                   AND
(A.EMP_ID ,A.ATTEND_DATE) NOT IN (
        SELECT EMP_ID ,ADJ_DATE
        FROM HR_NIGHTBILL_ADJUST
        WHERE 
        COMPANY_CODE=:P_COMPANY_CODE AND
        COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE AND
        INIT_YR(TO_CHAR(ADJ_DATE,'MM/YYYY')) =  INIT_YR(:P_MNYR) )  AND 
A.COMPANY_CODE                                  = :P_COMPANY_CODE      AND
A.COMPANY_BRANCH_CODE                           = :P_COMPANY_BRANCH_CODE      AND
(S.DESIG_GROUP                                  = :P_DESIG_GROUP OR :P_DESIG_GROUP IS NULL)     AND
(B.DEPT_GROUP                                   = :P_DEPT_GROUP OR :P_DEPT_GROUP IS NULL)       AND
(B.DEPT_CODE                                    = :P_DEPT_CODE OR :P_DEPT_CODE IS NULL)      AND
(A.EMP_ID                                       = :P_EMP OR :P_EMP IS NULL)         AND
TO_CHAR(A.ATTEND_DATE,'MM/YYYY') = :P_MNYR    

UNION

SELECT DISTINCT B.JOIN_DT,B.BANK_SAL_FLAG,B.EMP_AC_NO,B.EMP_AC_DATE,B.MOBILE_BANK_SAL_FLAG,B.MOBILE_AC_NO,B.MOBILE_AC_DATE, A.ADJ_DATE ,
TO_CHAR(A.ADJ_DATE,'DY') DD,A.EMP_ID,B.NAME,NULL IN_TIME,NULL OUT_TIME,
B.BASIC_SALARY,B.DEPT_GROUP,B.DEPT_CODE,B.DESIG_CODE,S.DESIG_GROUP,B.SALARY_TYPE
FROM HR_NIGHTBILL_ADJUST A, EMP B, DESIGNATION S
WHERE 
A.COMPANY_CODE                                   =B.COMPANY_CODE     AND
A.COMPANY_BRANCH_CODE                            =B.COMPANY_BRANCH_CODE    AND
A.EMP_ID                                         =B.EMP_ID    AND
B.DEPT_GROUP                                     = S.DEPT_GROUP  AND
B.DEPT_CODE                                      = S.DEPT_CODE  AND
B.DESIG_CODE                                     = S.DESIG_CODE AND
(A.EMP_ID ,A.ADJ_DATE) NOT IN (
        SELECT EMP_ID ,ADJ_DATE
        FROM HR_NIGHTBILL_ADJUST
        WHERE 
        COMPANY_CODE=:P_COMPANY_CODE AND
        COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE AND
        ( ADJUST_FLAG IS NULL ) OR
        ( ADJUST_FLAG ='-' ) AND
        INIT_YR(TO_CHAR(ADJ_DATE,'MM/YYYY')) =  INIT_YR(:P_MNYR) )  AND       
A.COMPANY_CODE                                  = :P_COMPANY_CODE      AND
A.COMPANY_BRANCH_CODE                           = :P_COMPANY_BRANCH_CODE      AND
(S.DESIG_GROUP                                  = :P_DESIG_GROUP OR :P_DESIG_GROUP IS NULL)     AND
(B.DEPT_GROUP                                   = :P_DEPT_GROUP OR :P_DEPT_GROUP IS NULL)       AND
(B.DEPT_CODE                                    = :P_DEPT_CODE OR :P_DEPT_CODE IS NULL)      AND
(A.EMP_ID                                       = :P_EMP OR :P_EMP IS NULL)         AND
TO_CHAR(A.ADJ_DATE,'MM/YYYY') = :P_MNYR   )                               
ORDER BY 
ATTEND_DATE,
DEPT_CODE  ) X)                              

ORDER BY 
DEPT_GROUP, DEPT_CODE, DESIG_CODE, ATTEND_DATE

-------------------------------------------Night Allowance Query End ----------------------------------------------------


-------------------------------------------Night Allowance Summary Query Start --------------------------------------------

SELECT
EMP_ID, NAME, DESIGNATION, ACCOUNT_NO, 
(SELECT NVL(O.NIGHT_ALL,0) FROM HR_TNOFF_ALLOWANCE O
WHERE O.DEPT_GROUP  = Y.DEPT_GROUP 
AND O.DEPT_CODE   =  Y.DEPT_CODE  
AND O.DESIG_CODE  = Y.DESIG_CODE 
AND O.EFFECTIVE_DATE  = (SELECT MAX(EFFECTIVE_DATE) 
                     FROM HR_TNOFF_ALLOWANCE 
                     WHERE DEPT_GROUP = Y.DEPT_GROUP AND
                     DEPT_CODE        = Y.DEPT_CODE  AND
                     DESIG_CODE      = Y.DESIG_CODE AND
                     EFFECTIVE_DATE  <= TO_DATE(:P_MNYR,'MM/YYYY'))) ALL_PER_DAY,
COUNT(ATTEND_DATE)  QTY , SUM(NET_PAYABLE_BANK) BANK, SUM(NET_PAYABLE_CASH) CASH,
DEPT_GROUP, DEPT_CODE, DESIG_CODE,DEPARTMENT, SECTION_NAME 
FROM (SELECT
NAME, DESIGNATION, DEPARTMENT, SECTION_NAME, ATTEND_DATE , JOIN_DT, DD, EMP_ID,
DEPT_GROUP, DEPT_CODE, DESIG_CODE, DESIG_GROUP,
(CASE 
WHEN DESIG_GROUP ='OF' THEN EMP_AC_NO
WHEN DESIG_GROUP ='FW' THEN MOBILE_AC_NO
WHEN DESIG_GROUP ='OS' THEN MOBILE_AC_NO
ELSE NULL END) as ACCOUNT_NO,
(CASE 
WHEN EMP_AC_NO IS NOT NULL AND BANK_SAL_FLAG IS NOT NULL 
    OR MOBILE_AC_NO IS NOT NULL AND MOBILE_BANK_SAL_FLAG IS NOT NULL THEN
    NVL(NIGHT_ALL, 0)
ELSE 0
END) as NET_PAYABLE_BANK,
(CASE
WHEN EMP_AC_NO IS NULL AND BANK_SAL_FLAG IS NULL AND MOBILE_AC_NO IS NULL AND MOBILE_BANK_SAL_FLAG IS NULL THEN
    NVL(NIGHT_ALL, 0)
ELSE 0
END) as NET_PAYABLE_CASH

FROM (SELECT 
(SELECT ' '||O.DESIG_DESC FROM DESIGNATION O WHERE O.DEPT_GROUP = X.DEPT_GROUP AND O.DEPT_CODE  = X.DEPT_CODE AND O.DESIG_CODE = X.DESIG_CODE) as DESIGNATION,
(SELECT ' '||O.DEPT_GROUP_NAME FROM DEPT_GROUP O WHERE O.DEPT_GROUP_CODE = X.DEPT_GROUP) as DEPARTMENT,
(SELECT ' '||O.DEPT_DESC FROM DEPT O WHERE O.DEPT_GROUP = X.DEPT_GROUP AND O.DEPT_CODE  = X.DEPT_CODE) as SECTION_NAME,
ATTEND_DATE , DD, EMP_ID, NAME, BANK_SAL_FLAG,EMP_AC_NO,EMP_AC_DATE,MOBILE_BANK_SAL_FLAG,MOBILE_AC_NO,
MOBILE_AC_DATE, DEPT_GROUP, DEPT_CODE, DESIG_CODE, DESIG_GROUP, JOIN_DT,
(SELECT NVL(O.NIGHT_ALL,0) FROM HR_TNOFF_ALLOWANCE O
WHERE O.DEPT_GROUP  = X.DEPT_GROUP 
AND O.DEPT_CODE   =  X.DEPT_CODE  
AND O.DESIG_CODE  = X.DESIG_CODE 
AND O.EFFECTIVE_DATE  = (SELECT MAX(EFFECTIVE_DATE) 
                     FROM HR_TNOFF_ALLOWANCE 
                     WHERE DEPT_GROUP = X.DEPT_GROUP AND
                     DEPT_CODE        = X.DEPT_CODE  AND
                     DESIG_CODE      = X.DESIG_CODE AND
                     EFFECTIVE_DATE  <= TO_DATE(:P_MNYR,'MM/YYYY'))) NIGHT_ALL
FROM (SELECT JOIN_DT,BANK_SAL_FLAG,EMP_AC_NO,EMP_AC_DATE,MOBILE_BANK_SAL_FLAG,MOBILE_AC_NO,MOBILE_AC_DATE,ATTEND_DATE ,
DD,EMP_ID,NAME,IN_TIME,OUT_TIME,BASIC_SALARY,DEPT_GROUP,DEPT_CODE,DESIG_CODE,DESIG_GROUP,SALARY_TYPE
FROM
(SELECT DISTINCT B.JOIN_DT,B.BANK_SAL_FLAG,B.EMP_AC_NO,B.EMP_AC_DATE,B.MOBILE_BANK_SAL_FLAG,B.MOBILE_AC_NO,B.MOBILE_AC_DATE, A.ATTEND_DATE ,
TO_CHAR(A.ATTEND_DATE,'DY') DD,A.EMP_ID,B.NAME,TO_CHAR(A.IN_TIME,'HH12:MI AM') IN_TIME,TO_CHAR(A.OUT_TIME,'HH12:MI PM') OUT_TIME,
B.BASIC_SALARY,B.DEPT_GROUP,B.DEPT_CODE,B.DESIG_CODE,S.DESIG_GROUP,B.SALARY_TYPE
FROM DAILY_ATTENDANCE A, EMP B, DESIGNATION S
WHERE 
A.COMPANY_CODE                                   =B.COMPANY_CODE     AND
A.COMPANY_BRANCH_CODE                            =B.COMPANY_BRANCH_CODE    AND
A.EMP_ID                                         =B.EMP_ID    AND
B.DEPT_GROUP                                     = S.DEPT_GROUP  AND
B.DEPT_CODE                                      = S.DEPT_CODE  AND
B.DESIG_CODE                                     = S.DESIG_CODE AND
A.ATTEND_DATE != A.OUT_DATE                   AND
(A.EMP_ID ,A.ATTEND_DATE) NOT IN (
        SELECT EMP_ID ,ADJ_DATE
        FROM HR_NIGHTBILL_ADJUST
        WHERE 
        COMPANY_CODE=:P_COMPANY_CODE AND
        COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE AND
        INIT_YR(TO_CHAR(ADJ_DATE,'MM/YYYY')) =  INIT_YR(:P_MNYR) )  AND 
A.COMPANY_CODE                                  = :P_COMPANY_CODE      AND
A.COMPANY_BRANCH_CODE                           = :P_COMPANY_BRANCH_CODE      AND
(S.DESIG_GROUP                                  = :P_DESIG_GROUP OR :P_DESIG_GROUP IS NULL)     AND
(B.DEPT_GROUP                                   = :P_DEPT_GROUP OR :P_DEPT_GROUP IS NULL)       AND
(B.DEPT_CODE                                    = :P_DEPT_CODE OR :P_DEPT_CODE IS NULL)      AND
(A.EMP_ID                                       = :P_EMP OR :P_EMP IS NULL)         AND
TO_CHAR(A.ATTEND_DATE,'MM/YYYY') = :P_MNYR    

UNION

SELECT DISTINCT B.JOIN_DT,B.BANK_SAL_FLAG,B.EMP_AC_NO,B.EMP_AC_DATE,B.MOBILE_BANK_SAL_FLAG,B.MOBILE_AC_NO,B.MOBILE_AC_DATE, A.ADJ_DATE ,
TO_CHAR(A.ADJ_DATE,'DY') DD,A.EMP_ID,B.NAME,NULL IN_TIME,NULL OUT_TIME,
B.BASIC_SALARY,B.DEPT_GROUP,B.DEPT_CODE,B.DESIG_CODE,S.DESIG_GROUP,B.SALARY_TYPE
FROM HR_NIGHTBILL_ADJUST A, EMP B, DESIGNATION S
WHERE 
A.COMPANY_CODE                                   =B.COMPANY_CODE     AND
A.COMPANY_BRANCH_CODE                            =B.COMPANY_BRANCH_CODE    AND
A.EMP_ID                                         =B.EMP_ID    AND
B.DEPT_GROUP                                     = S.DEPT_GROUP  AND
B.DEPT_CODE                                      = S.DEPT_CODE  AND
B.DESIG_CODE                                     = S.DESIG_CODE AND
(A.EMP_ID ,A.ADJ_DATE) NOT IN (
        SELECT EMP_ID ,ADJ_DATE
        FROM HR_NIGHTBILL_ADJUST
        WHERE 
        COMPANY_CODE=:P_COMPANY_CODE AND
        COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE AND
        ( ADJUST_FLAG IS NULL ) OR
        ( ADJUST_FLAG ='-' ) AND
        INIT_YR(TO_CHAR(ADJ_DATE,'MM/YYYY')) =  INIT_YR(:P_MNYR) )  AND       
A.COMPANY_CODE                                  = :P_COMPANY_CODE      AND
A.COMPANY_BRANCH_CODE                           = :P_COMPANY_BRANCH_CODE      AND
(S.DESIG_GROUP                                  = :P_DESIG_GROUP OR :P_DESIG_GROUP IS NULL)     AND
(B.DEPT_GROUP                                   = :P_DEPT_GROUP OR :P_DEPT_GROUP IS NULL)       AND
(B.DEPT_CODE                                    = :P_DEPT_CODE OR :P_DEPT_CODE IS NULL)      AND
(A.EMP_ID                                       = :P_EMP OR :P_EMP IS NULL)         AND
TO_CHAR(A.ADJ_DATE,'MM/YYYY') = :P_MNYR   )                               
ORDER BY 
ATTEND_DATE,
DEPT_CODE  ) X)) Y
GROUP BY EMP_ID, NAME, DESIGNATION, ACCOUNT_NO,  DEPARTMENT, SECTION_NAME,   
DEPT_GROUP, DEPT_CODE, DESIG_CODE   
ORDER BY 
DEPT_GROUP, DEPT_CODE, DESIG_CODE,EMP_ID

-------------------------------------------Night Allowance Summary Query End --------------------------------------------
-------------------------------------------Night Allowance Compare Query Start --------------------------------------------
SELECT 
DEPT_GROUP, DEPARTMENT, DEPT_CODE, SECTION_NAME, SUM(TOT_STAFF) TOT_STAFF, SUM(PAYABLE_DAYS) PAYABLE_DAYS, SUM(PAYABLE_AMT) PAYABLE_AMT, SUM(TOT_STAFF_P) TOT_STAFF_P, SUM(PAYABLE_DAYS_P) PAYABLE_DAYS_P, SUM(PAYABLE_AMT_P) PAYABLE_AMT_P,
TO_CHAR(ADD_MONTHS(TO_DATE(:P_MNYR, 'MM/YYYY'),-1), 'fmMonth-YYYY') PREV_MONTH,  TO_CHAR(TO_DATE(:P_MNYR, 'MM/YYYY'), 'fmMonth-YYYY') THIS_MONTH
FROM ((SELECT
DEPT_GROUP, DEPARTMENT, DEPT_CODE, SECTION_NAME, COUNT(DISTINCT EMP_ID) TOT_STAFF, COUNT(ATTEND_DATE) PAYABLE_DAYS, SUM(NIGHT_ALL) PAYABLE_AMT, NULL TOT_STAFF_P, NULL PAYABLE_DAYS_P, NULL PAYABLE_AMT_P
FROM (SELECT 
(SELECT ' '||O.DESIG_DESC FROM DESIGNATION O WHERE O.DEPT_GROUP = X.DEPT_GROUP AND O.DEPT_CODE  = X.DEPT_CODE AND O.DESIG_CODE = X.DESIG_CODE) as DESIGNATION,
(SELECT ' '||O.DEPT_GROUP_NAME FROM DEPT_GROUP O WHERE O.DEPT_GROUP_CODE = X.DEPT_GROUP) as DEPARTMENT,
(SELECT ' '||O.DEPT_DESC FROM DEPT O WHERE O.DEPT_GROUP = X.DEPT_GROUP AND O.DEPT_CODE  = X.DEPT_CODE) as SECTION_NAME,
ATTEND_DATE , DD, EMP_ID, NAME, BANK_SAL_FLAG,EMP_AC_NO,EMP_AC_DATE,MOBILE_BANK_SAL_FLAG,MOBILE_AC_NO,
MOBILE_AC_DATE, DEPT_GROUP, DEPT_CODE, DESIG_CODE, DESIG_GROUP, JOIN_DT,
(SELECT NVL(O.NIGHT_ALL,0) FROM HR_TNOFF_ALLOWANCE O
WHERE O.DEPT_GROUP  = X.DEPT_GROUP 
AND O.DEPT_CODE   =  X.DEPT_CODE  
AND O.DESIG_CODE  = X.DESIG_CODE 
AND O.EFFECTIVE_DATE  = (SELECT MAX(EFFECTIVE_DATE) 
                     FROM HR_TNOFF_ALLOWANCE 
                     WHERE DEPT_GROUP = X.DEPT_GROUP AND
                     DEPT_CODE        = X.DEPT_CODE  AND
                     DESIG_CODE      = X.DESIG_CODE AND
                     EFFECTIVE_DATE  <= TO_DATE(:P_MNYR,'MM/YYYY'))) NIGHT_ALL
FROM (SELECT JOIN_DT,BANK_SAL_FLAG,EMP_AC_NO,EMP_AC_DATE,MOBILE_BANK_SAL_FLAG,MOBILE_AC_NO,MOBILE_AC_DATE,ATTEND_DATE ,
DD,EMP_ID,NAME,IN_TIME,OUT_TIME,BASIC_SALARY,DEPT_GROUP,DEPT_CODE,DESIG_CODE,DESIG_GROUP,SALARY_TYPE
FROM
(SELECT DISTINCT B.JOIN_DT,B.BANK_SAL_FLAG,B.EMP_AC_NO,B.EMP_AC_DATE,B.MOBILE_BANK_SAL_FLAG,B.MOBILE_AC_NO,B.MOBILE_AC_DATE, A.ATTEND_DATE ,
TO_CHAR(A.ATTEND_DATE,'DY') DD,A.EMP_ID,B.NAME,TO_CHAR(A.IN_TIME,'HH12:MI AM') IN_TIME,TO_CHAR(A.OUT_TIME,'HH12:MI PM') OUT_TIME,
B.BASIC_SALARY,B.DEPT_GROUP,B.DEPT_CODE,B.DESIG_CODE,S.DESIG_GROUP,B.SALARY_TYPE
FROM DAILY_ATTENDANCE A, EMP B, DESIGNATION S
WHERE 
A.COMPANY_CODE                                   =B.COMPANY_CODE     AND
A.COMPANY_BRANCH_CODE                            =B.COMPANY_BRANCH_CODE    AND
A.EMP_ID                                         =B.EMP_ID    AND
B.DEPT_GROUP                                     = S.DEPT_GROUP  AND
B.DEPT_CODE                                      = S.DEPT_CODE  AND
B.DESIG_CODE                                     = S.DESIG_CODE AND
A.ATTEND_DATE != A.OUT_DATE                   AND
(A.EMP_ID ,A.ATTEND_DATE) NOT IN (
        SELECT EMP_ID ,ADJ_DATE
        FROM HR_NIGHTBILL_ADJUST
        WHERE 
        COMPANY_CODE=:P_COMPANY_CODE AND
        COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE AND
        INIT_YR(TO_CHAR(ADJ_DATE,'MM/YYYY')) =  INIT_YR(:P_MNYR) )  AND 
A.COMPANY_CODE                                  = :P_COMPANY_CODE      AND
A.COMPANY_BRANCH_CODE                           = :P_COMPANY_BRANCH_CODE      AND
(S.DESIG_GROUP                                  = :P_DESIG_GROUP OR :P_DESIG_GROUP IS NULL)     AND
(B.DEPT_GROUP                                   = :P_DEPT_GROUP OR :P_DEPT_GROUP IS NULL)       AND
(B.DEPT_CODE                                    = :P_DEPT_CODE OR :P_DEPT_CODE IS NULL)      AND
(A.EMP_ID                                       = :P_EMP OR :P_EMP IS NULL)         AND
TO_CHAR(A.ATTEND_DATE,'MM/YYYY') = :P_MNYR    

UNION

SELECT DISTINCT B.JOIN_DT,B.BANK_SAL_FLAG,B.EMP_AC_NO,B.EMP_AC_DATE,B.MOBILE_BANK_SAL_FLAG,B.MOBILE_AC_NO,B.MOBILE_AC_DATE, A.ADJ_DATE ,
TO_CHAR(A.ADJ_DATE,'DY') DD,A.EMP_ID,B.NAME,NULL IN_TIME,NULL OUT_TIME,
B.BASIC_SALARY,B.DEPT_GROUP,B.DEPT_CODE,B.DESIG_CODE,S.DESIG_GROUP,B.SALARY_TYPE
FROM HR_NIGHTBILL_ADJUST A, EMP B, DESIGNATION S
WHERE 
A.COMPANY_CODE                                   =B.COMPANY_CODE     AND
A.COMPANY_BRANCH_CODE                            =B.COMPANY_BRANCH_CODE    AND
A.EMP_ID                                         =B.EMP_ID    AND
B.DEPT_GROUP                                     = S.DEPT_GROUP  AND
B.DEPT_CODE                                      = S.DEPT_CODE  AND
B.DESIG_CODE                                     = S.DESIG_CODE AND
(A.EMP_ID ,A.ADJ_DATE) NOT IN (
        SELECT EMP_ID ,ADJ_DATE
        FROM HR_NIGHTBILL_ADJUST
        WHERE 
        COMPANY_CODE=:P_COMPANY_CODE AND
        COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE AND
        ( ADJUST_FLAG IS NULL ) OR
        ( ADJUST_FLAG ='-' ) AND
        INIT_YR(TO_CHAR(ADJ_DATE,'MM/YYYY')) =  INIT_YR(:P_MNYR) )  AND       
A.COMPANY_CODE                                  = :P_COMPANY_CODE      AND
A.COMPANY_BRANCH_CODE                           = :P_COMPANY_BRANCH_CODE      AND
(S.DESIG_GROUP                                  = :P_DESIG_GROUP OR :P_DESIG_GROUP IS NULL)     AND
(B.DEPT_GROUP                                   = :P_DEPT_GROUP OR :P_DEPT_GROUP IS NULL)       AND
(B.DEPT_CODE                                    = :P_DEPT_CODE OR :P_DEPT_CODE IS NULL)      AND
(A.EMP_ID                                       = :P_EMP OR :P_EMP IS NULL)         AND
TO_CHAR(A.ADJ_DATE,'MM/YYYY') = :P_MNYR   )                               
ORDER BY 
ATTEND_DATE,
DEPT_CODE  ) X)
GROUP BY 
DEPT_GROUP, DEPARTMENT, DEPT_CODE, SECTION_NAME)

UNION

(SELECT
DEPT_GROUP, DEPARTMENT, DEPT_CODE, SECTION_NAME, NULL TOT_STAFF, NULL PAYABLE_DAYS, NULL PAYABLE_AMT, COUNT(DISTINCT EMP_ID) TOT_STAFF_P, COUNT(ATTEND_DATE) PAYABLE_DAYS_P, SUM(NIGHT_ALL) PAYABLE_AMT_P
FROM (SELECT 
(SELECT ' '||O.DESIG_DESC FROM DESIGNATION O WHERE O.DEPT_GROUP = X.DEPT_GROUP AND O.DEPT_CODE  = X.DEPT_CODE AND O.DESIG_CODE = X.DESIG_CODE) as DESIGNATION,
(SELECT ' '||O.DEPT_GROUP_NAME FROM DEPT_GROUP O WHERE O.DEPT_GROUP_CODE = X.DEPT_GROUP) as DEPARTMENT,
(SELECT ' '||O.DEPT_DESC FROM DEPT O WHERE O.DEPT_GROUP = X.DEPT_GROUP AND O.DEPT_CODE  = X.DEPT_CODE) as SECTION_NAME,
ATTEND_DATE , DD, EMP_ID, NAME, BANK_SAL_FLAG,EMP_AC_NO,EMP_AC_DATE,MOBILE_BANK_SAL_FLAG,MOBILE_AC_NO,
MOBILE_AC_DATE, DEPT_GROUP, DEPT_CODE, DESIG_CODE, DESIG_GROUP, JOIN_DT,
(SELECT NVL(O.NIGHT_ALL,0) FROM HR_TNOFF_ALLOWANCE O
WHERE O.DEPT_GROUP  = X.DEPT_GROUP 
AND O.DEPT_CODE   =  X.DEPT_CODE  
AND O.DESIG_CODE  = X.DESIG_CODE 
AND O.EFFECTIVE_DATE  = (SELECT MAX(EFFECTIVE_DATE) 
                     FROM HR_TNOFF_ALLOWANCE 
                     WHERE DEPT_GROUP = X.DEPT_GROUP AND
                     DEPT_CODE        = X.DEPT_CODE  AND
                     DESIG_CODE      = X.DESIG_CODE AND
                     EFFECTIVE_DATE  <= TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:P_MNYR, 'MM/YYYY'),-1), 'MM/YYYY'),'MM/YYYY'))) NIGHT_ALL
FROM (SELECT JOIN_DT,BANK_SAL_FLAG,EMP_AC_NO,EMP_AC_DATE,MOBILE_BANK_SAL_FLAG,MOBILE_AC_NO,MOBILE_AC_DATE,ATTEND_DATE ,
DD,EMP_ID,NAME,IN_TIME,OUT_TIME,BASIC_SALARY,DEPT_GROUP,DEPT_CODE,DESIG_CODE,DESIG_GROUP,SALARY_TYPE
FROM
(SELECT DISTINCT B.JOIN_DT,B.BANK_SAL_FLAG,B.EMP_AC_NO,B.EMP_AC_DATE,B.MOBILE_BANK_SAL_FLAG,B.MOBILE_AC_NO,B.MOBILE_AC_DATE, A.ATTEND_DATE ,
TO_CHAR(A.ATTEND_DATE,'DY') DD,A.EMP_ID,B.NAME,TO_CHAR(A.IN_TIME,'HH12:MI AM') IN_TIME,TO_CHAR(A.OUT_TIME,'HH12:MI PM') OUT_TIME,
B.BASIC_SALARY,B.DEPT_GROUP,B.DEPT_CODE,B.DESIG_CODE,S.DESIG_GROUP,B.SALARY_TYPE
FROM DAILY_ATTENDANCE A, EMP B, DESIGNATION S
WHERE 
A.COMPANY_CODE                                   =B.COMPANY_CODE     AND
A.COMPANY_BRANCH_CODE                            =B.COMPANY_BRANCH_CODE    AND
A.EMP_ID                                         =B.EMP_ID    AND
B.DEPT_GROUP                                     = S.DEPT_GROUP  AND
B.DEPT_CODE                                      = S.DEPT_CODE  AND
B.DESIG_CODE                                     = S.DESIG_CODE AND
A.ATTEND_DATE != A.OUT_DATE                   AND
(A.EMP_ID ,A.ATTEND_DATE) NOT IN (
        SELECT EMP_ID ,ADJ_DATE
        FROM HR_NIGHTBILL_ADJUST
        WHERE 
        COMPANY_CODE=:P_COMPANY_CODE AND
        COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE AND
        INIT_YR(TO_CHAR(ADJ_DATE,'MM/YYYY')) =  INIT_YR(TO_CHAR(ADD_MONTHS(TO_DATE(:P_MNYR, 'MM/YYYY'),-1), 'MM/YYYY')) )  AND 
A.COMPANY_CODE                                  = :P_COMPANY_CODE      AND
A.COMPANY_BRANCH_CODE                           = :P_COMPANY_BRANCH_CODE      AND
(S.DESIG_GROUP                                  = :P_DESIG_GROUP OR :P_DESIG_GROUP IS NULL)     AND
(B.DEPT_GROUP                                   = :P_DEPT_GROUP OR :P_DEPT_GROUP IS NULL)       AND
(B.DEPT_CODE                                    = :P_DEPT_CODE OR :P_DEPT_CODE IS NULL)      AND
(A.EMP_ID                                       = :P_EMP OR :P_EMP IS NULL)         AND
TO_CHAR(A.ATTEND_DATE,'MM/YYYY') = TO_CHAR(ADD_MONTHS(TO_DATE(:P_MNYR, 'MM/YYYY'),-1), 'MM/YYYY')    

UNION

SELECT DISTINCT B.JOIN_DT,B.BANK_SAL_FLAG,B.EMP_AC_NO,B.EMP_AC_DATE,B.MOBILE_BANK_SAL_FLAG,B.MOBILE_AC_NO,B.MOBILE_AC_DATE, A.ADJ_DATE ,
TO_CHAR(A.ADJ_DATE,'DY') DD,A.EMP_ID,B.NAME,NULL IN_TIME,NULL OUT_TIME,
B.BASIC_SALARY,B.DEPT_GROUP,B.DEPT_CODE,B.DESIG_CODE,S.DESIG_GROUP,B.SALARY_TYPE
FROM HR_NIGHTBILL_ADJUST A, EMP B, DESIGNATION S
WHERE 
A.COMPANY_CODE                                   =B.COMPANY_CODE     AND
A.COMPANY_BRANCH_CODE                            =B.COMPANY_BRANCH_CODE    AND
A.EMP_ID                                         =B.EMP_ID    AND
B.DEPT_GROUP                                     = S.DEPT_GROUP  AND
B.DEPT_CODE                                      = S.DEPT_CODE  AND
B.DESIG_CODE                                     = S.DESIG_CODE AND
(A.EMP_ID ,A.ADJ_DATE) NOT IN (
        SELECT EMP_ID ,ADJ_DATE
        FROM HR_NIGHTBILL_ADJUST
        WHERE 
        COMPANY_CODE=:P_COMPANY_CODE AND
        COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE AND
        ( ADJUST_FLAG IS NULL ) OR
        ( ADJUST_FLAG ='-' ) AND
        INIT_YR(TO_CHAR(ADJ_DATE,'MM/YYYY')) =  INIT_YR(TO_CHAR(ADD_MONTHS(TO_DATE(:P_MNYR, 'MM/YYYY'),-1), 'MM/YYYY')) )  AND       
A.COMPANY_CODE                                  = :P_COMPANY_CODE      AND
A.COMPANY_BRANCH_CODE                           = :P_COMPANY_BRANCH_CODE      AND
(S.DESIG_GROUP                                  = :P_DESIG_GROUP OR :P_DESIG_GROUP IS NULL)     AND
(B.DEPT_GROUP                                   = :P_DEPT_GROUP OR :P_DEPT_GROUP IS NULL)       AND
(B.DEPT_CODE                                    = :P_DEPT_CODE OR :P_DEPT_CODE IS NULL)      AND
(A.EMP_ID                                       = :P_EMP OR :P_EMP IS NULL)         AND
TO_CHAR(A.ADJ_DATE,'MM/YYYY') = TO_CHAR(ADD_MONTHS(TO_DATE(:P_MNYR, 'MM/YYYY'),-1), 'MM/YYYY')   )                               
ORDER BY 
ATTEND_DATE,
DEPT_CODE  ) X)
GROUP BY 
DEPT_GROUP, DEPARTMENT, DEPT_CODE, SECTION_NAME))  
GROUP BY DEPT_GROUP, DEPARTMENT, DEPT_CODE, SECTION_NAME
ORDER BY  DEPT_GROUP, DEPT_CODE

-------------------------------------------Night Allowance Compare Query End --------------------------------------------



-----------------------------------------PRE_BY----------------------------
SELECT 
(SELECT ' '||NAME
    FROM EMP 
    WHERE EMP_ID = A.EMP_ID) PRE_BY_NAME,
(SELECT ' '||DESIG_DESC
    FROM DESIGNATION
    WHERE
    DEPT_GROUP = B.DEPT_GROUP AND 
    DEPT_CODE = B.DEPT_CODE AND 
    DESIG_CODE =B.DESIG_CODE) PRE_BY_DESIG
FROM SIGNATURE A, EMP B
WHERE
A.COMPANY_CODE = B.COMPANY_CODE AND
A.COMPANY_BRANCH_CODE = B.COMPANY_BRANCH_CODE AND
A.EMP_ID = B.EMP_ID AND
A.COMPANY_BRANCH_CODE = :P_COMPANY_BRANCH_CODE AND
SIGNATORY_TYPE = 'PB' AND
SIGNATORY_FOR   ='HRM'

-----------------------------------------CHK_BY----------------------------

SELECT 
(SELECT ' '||NAME
    FROM EMP 
    WHERE EMP_ID = A.EMP_ID) CHK_BY_NAME,
(SELECT ' '||DESIG_DESC
    FROM DESIGNATION
    WHERE
    DEPT_GROUP = B.DEPT_GROUP AND 
    DEPT_CODE = B.DEPT_CODE AND 
    DESIG_CODE =B.DESIG_CODE) CHK_BY_DESIG
FROM SIGNATURE A, EMP B
WHERE
A.COMPANY_CODE = B.COMPANY_CODE AND
A.COMPANY_BRANCH_CODE = B.COMPANY_BRANCH_CODE AND
A.EMP_ID = B.EMP_ID AND
A.COMPANY_BRANCH_CODE = :P_COMPANY_BRANCH_CODE AND
SIGNATORY_TYPE = 'CB' AND
SIGNATORY_FOR   ='HRM'

-----------------------------------------REC_BY----------------------------

SELECT 
(SELECT ' '||NAME
    FROM EMP 
    WHERE EMP_ID = A.EMP_ID) REC_BY_NAME,
(SELECT ' '||DESIG_DESC
    FROM DESIGNATION
    WHERE
    DEPT_GROUP = B.DEPT_GROUP AND 
    DEPT_CODE = B.DEPT_CODE AND 
    DESIG_CODE =B.DESIG_CODE) REC_BY_DESIG
FROM SIGNATURE A, EMP B
WHERE
A.COMPANY_CODE = B.COMPANY_CODE AND
A.COMPANY_BRANCH_CODE = B.COMPANY_BRANCH_CODE AND
A.EMP_ID = B.EMP_ID AND
A.COMPANY_BRANCH_CODE = :P_COMPANY_BRANCH_CODE AND
SIGNATORY_TYPE = 'RB' AND
SIGNATORY_FOR   ='HRM'

-----------------------------------------AUD_BY----------------------------


SELECT 
(SELECT ' '||NAME
    FROM EMP 
    WHERE EMP_ID = A.EMP_ID) AUD_BY_NAME,
(SELECT ' '||DESIG_DESC
    FROM DESIGNATION
    WHERE
    DEPT_GROUP = B.DEPT_GROUP AND 
    DEPT_CODE = B.DEPT_CODE AND 
    DESIG_CODE =B.DESIG_CODE) AUD_BY_DESIG
FROM SIGNATURE A, EMP B
WHERE
A.COMPANY_CODE = B.COMPANY_CODE AND
A.COMPANY_BRANCH_CODE = B.COMPANY_BRANCH_CODE AND
A.EMP_ID = B.EMP_ID AND
A.COMPANY_BRANCH_CODE = :P_COMPANY_BRANCH_CODE  AND
SIGNATORY_TYPE = 'AB' AND
SIGNATORY_FOR   ='HRM'  