-------------------------------------------Offday Allowance Query Start ----------------------------------------------------
SELECT 
NAME, DESIGNATION, DEPARTMENT, SECTION_NAME, ATTEND_DATE , DD, EMP_ID,DUTY,
BASIC_SALARY, JOIN_DT, BANK_SAL_FLAG, EMP_AC_NO, EMP_AC_DATE, MOBILE_BANK_SAL_FLAG, MOBILE_AC_NO, MOBILE_AC_DATE, DEPT_GROUP, DEPT_CODE, 
DESIG_CODE, SALARY_TYPE, DESIG_GROUP, DEPT_GROUP_SL, OFFDAY_ALL, OFFDAY_LUNCH_DIN_ALL, ACTUAL_TIME, 
IN_TIME, OUT_TIME, NVL(OFFDAY_ALL, 0)+NVL(OFFDAY_LUNCH_DIN_ALL, 0) as TOTAL_PAY_AMT,
(CASE 
WHEN EMP_AC_NO IS NOT NULL AND BANK_SAL_FLAG IS NOT NULL 
	OR MOBILE_AC_NO IS NOT NULL AND MOBILE_BANK_SAL_FLAG IS NOT NULL THEN
	NVL(OFFDAY_ALL, 0)+NVL(OFFDAY_LUNCH_DIN_ALL, 0)
ELSE 0
END) as NET_PAYABLE_BANK,

(CASE
WHEN EMP_AC_NO IS NULL AND BANK_SAL_FLAG IS NULL AND MOBILE_AC_NO IS NULL AND MOBILE_BANK_SAL_FLAG IS NULL THEN
	NVL(OFFDAY_ALL, 0)+NVL(OFFDAY_LUNCH_DIN_ALL, 0)
ELSE 0
END) as NET_PAYABLE_CASH 
FROM (SELECT
NAME, DESIGNATION, DEPARTMENT, SECTION_NAME, ATTEND_DATE , DD, EMP_ID,DUTY,
BASIC_SALARY, JOIN_DT, EMP_AC_NO, EMP_AC_DATE, MOBILE_AC_NO, MOBILE_AC_DATE, DEPT_GROUP, DEPT_CODE, 
DESIG_CODE, SALARY_TYPE, DESIG_GROUP, DEPT_GROUP_SL, BANK_SAL_FLAG, MOBILE_BANK_SAL_FLAG,
(CASE 
WHEN PRE_ADJ_OFFDAY_ALL > 0 THEN 0
	ELSE PRE_OFFDAY_ALL
END) as OFFDAY_ALL,

(CASE 
WHEN PRE_ADJ_OFFDAY_LUNCH_ALL > 0 THEN 0
ELSE 
 CASE WHEN OUT_TIME1 IS NOT NULL AND OUT_TIME1>= TO_CHAR(TO_DATE('1400','HH24:MI'),'HH24:MI')  AND OUT_TIME1< TO_CHAR(TO_DATE('23:00','HH24:MI'),'HH24:MI') OR
 DUTY > 4 THEN 
  PRE_OFFDAY_LUNCH_ALL
 ELSE
	CASE WHEN ADJ_OFFDAY_LUNCH_ALL > 0 THEN PRE_OFFDAY_LUNCH_ALL
	ELSE 0
	END
 END	
END) as OFFDAY_LUNCH_DIN_ALL,

(CASE 
  WHEN OUT_TIME_DATE> IN_TIME_DATE THEN 
	ROUND(24*(OUT_TIME_DATE-IN_TIME_DATE))
  WHEN IN_TIME_DATE > OUT_TIME_DATE  THEN 
    ROUND(24*(IN_TIME_DATE-OUT_TIME_DATE))
  WHEN OUT_TIME_DATE IS NULL  THEN 1
END) as ACTUAL_TIME, 
(CASE
WHEN PRE_IN_TIME > 0 THEN ORIGIN_IN_TIME
ELSE
IN_TIME1
END) as IN_TIME,

(CASE
WHEN PRE_IN_TIME > 0 THEN ORIGIN_OUT_TIME
ELSE
OUT_TIME1
END) as OUT_TIME
FROM (SELECT 
(SELECT ' '||O.DESIG_DESC FROM DESIGNATION O WHERE O.DEPT_GROUP = X.DEPT_GROUP AND O.DEPT_CODE  = X.DEPT_CODE AND O.DESIG_CODE = X.DESIG_CODE) as DESIGNATION,
(SELECT ' '||O.DEPT_GROUP_NAME FROM DEPT_GROUP O WHERE O.DEPT_GROUP_CODE = X.DEPT_GROUP) as DEPARTMENT,
(SELECT ' '||O.DEPT_DESC FROM DEPT O WHERE O.DEPT_GROUP = X.DEPT_GROUP AND O.DEPT_CODE  = X.DEPT_CODE) as SECTION_NAME,
ATTEND_DATE , DD, EMP_ID, NAME, IN_TIME as IN_TIME_DATE, OUT_TIME as OUT_TIME_DATE, IN_TIME1, OUT_TIME1, ROUND(24*(OUT_TIME-IN_TIME)) DUTY,
BASIC_SALARY, JOIN_DT,BANK_SAL_FLAG,EMP_AC_NO,EMP_AC_DATE,MOBILE_BANK_SAL_FLAG,MOBILE_AC_NO,
MOBILE_AC_DATE, DEPT_GROUP, DEPT_CODE, DESIG_CODE, SALARY_TYPE, DESIG_GROUP, DEPT_GROUP_SL,
(SELECT NVL(O.OFFDAY_ALL,0) FROM HR_TNOFF_ALLOWANCE O
WHERE O.DEPT_GROUP  = X.DEPT_GROUP 
AND O.DEPT_CODE   =  X.DEPT_CODE  
AND O.DESIG_CODE  = X.DESIG_CODE 
AND O.EFFECTIVE_DATE  = (SELECT MAX(EFFECTIVE_DATE) 
                     FROM HR_TNOFF_ALLOWANCE 
                     WHERE DEPT_GROUP = X.DEPT_GROUP AND
                     DEPT_CODE        = X.DEPT_CODE  AND
                     DESIG_CODE      = X.DESIG_CODE AND
                     EFFECTIVE_DATE  <= TO_DATE(:P_MNYR,'MM/YYYY'))) PRE_OFFDAY_ALL,
					 
(SELECT COUNT(O.EMP_ID) FROM HR_OFFDAY_ADJUST O
        WHERE O.COMPANY_CODE=:P_COMPANY_CODE
        AND O.COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE
		AND O.EMP_ID = X.EMP_ID 
		AND O.ADJ_DATE = X.ATTEND_DATE 
		AND O.OFFDAY_ADJUST ='C' 
		AND INIT_YR(TO_CHAR(O.ADJ_DATE,'MM/YYYY')) =  INIT_YR(:P_MNYR)) as PRE_ADJ_OFFDAY_ALL,
		
(SELECT NVL(O.OFFDAY_LUNCH_BILL,0) FROM HR_TNOFF_ALLOWANCE O
  WHERE O.DEPT_GROUP  = X.DEPT_GROUP 
  AND O.DEPT_CODE   =  X.DEPT_CODE  
  AND O.DESIG_CODE  = X.DESIG_CODE 
  AND O.EFFECTIVE_DATE  = (SELECT MAX(EFFECTIVE_DATE) 
		 FROM HR_TNOFF_ALLOWANCE 
		 WHERE DEPT_GROUP = X.DEPT_GROUP AND
		 DEPT_CODE        = X.DEPT_CODE  AND
		 DESIG_CODE      = x.DESIG_CODE AND
		 EFFECTIVE_DATE  <= TO_DATE(:P_MNYR,'MM/YYYY'))) as PRE_OFFDAY_LUNCH_ALL,
		 
(SELECT COUNT(O.EMP_ID) FROM HR_OFFDAY_ADJUST O
        WHERE O.COMPANY_CODE=:P_COMPANY_CODE
        AND O.COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE
		AND O.EMP_ID = X.EMP_ID 
		AND O.ADJ_DATE = X.ATTEND_DATE 
		AND O.LUNCH_ADJUST ='C' 
		AND INIT_YR(TO_CHAR(O.ADJ_DATE,'MM/YYYY')) =  INIT_YR(:P_MNYR)) as PRE_ADJ_OFFDAY_LUNCH_ALL,
		
(SELECT COUNT(EMP_ID) FROM HR_OFFDAY_ADJUST O
        WHERE O.COMPANY_CODE=:P_COMPANY_CODE 
		AND O.COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE
        AND O.EMP_ID = X.EMP_ID 
		AND O.ADJ_DATE = X.ATTEND_DATE 
		AND O.LUNCH_ADJUST ='A' 
		AND INIT_YR(TO_CHAR(O.ADJ_DATE,'MM/YYYY')) =  INIT_YR(:P_MNYR)) as ADJ_OFFDAY_LUNCH_ALL,
		
(SELECT COUNT(attend_date) from daily_attendance O
 WHERE O.EMP_ID = X.EMP_ID AND to_char(O.attend_date, 'MM/YYYY') = :P_MNYR
 AND O.attend_date = (SELECT adj_date FROM HR_OFFDAY_ADJUST WHERE emp_id = X.emp_id AND to_char(adj_date, 'MM/YYYY') = :P_MNYR and adj_date = X.attend_date )) as PRE_IN_TIME,
 
(SELECT to_char(O.in_time, 'HH24:MI') from daily_attendance O
 WHERE O.EMP_ID = X.EMP_ID
 AND to_char(O.attend_date, 'MM/YYYY') = :P_MNYR
 AND O.attend_date = X.attend_date) as ORIGIN_IN_TIME,
 
 (SELECT to_char(O.out_time, 'HH24:MI') from daily_attendance O
 WHERE O.EMP_ID = X.EMP_ID
 AND to_char(O.attend_date, 'MM/YYYY') = :P_MNYR
 AND O.attend_date = X.attend_date) as ORIGIN_OUT_TIME
 
FROM (SELECT DISTINCT A.ATTEND_DATE ,TO_CHAR(A.ATTEND_DATE,'DY') DD,A.EMP_ID,B.NAME,A.IN_TIME,A.OUT_TIME,TO_CHAR(A.IN_TIME,'HH24:MI') IN_TIME1,
B.BASIC_SALARY,TO_CHAR(A.OUT_TIME,'HH24:MI') OUT_TIME1,B.JOIN_DT,B.BANK_SAL_FLAG,B.EMP_AC_NO,B.EMP_AC_DATE,B.MOBILE_BANK_SAL_FLAG,B.MOBILE_AC_NO,
B.MOBILE_AC_DATE, B.DEPT_GROUP,B.DEPT_CODE,B.DESIG_CODE,B.SALARY_TYPE,S.DESIG_GROUP ,G.DEPT_GROUP_SL
FROM DAILY_ATTENDANCE A, EMP B, DESIGNATION S, DEPT_GROUP G
WHERE 
(B.DEPT_GROUP = G.DEPT_GROUP_CODE) AND
A.COMPANY_CODE =B.COMPANY_CODE AND
A.COMPANY_BRANCH_CODE=B.COMPANY_BRANCH_CODE AND
A.EMP_ID=B.EMP_ID AND
A.ATTEND_DATE IN 
		(
		SELECT HOLIDAY_DATE
		FROM HOLIDAY_WEEK
		WHERE COMPANY_CODE = :P_COMPANY_CODE AND
        COMPANY_BRANCH_CODE = :P_COMPANY_BRANCH_CODE AND
        INIT_YR(TO_CHAR(HOLIDAY_DATE,'MM/YYYY')) = INIT_YR(:P_MNYR)
		UNION
		SELECT DATE_TO
        FROM HOLIDAY
        WHERE 
        COMPANY_CODE = :P_COMPANY_CODE AND
        COMPANY_BRANCH_CODE = :P_COMPANY_BRANCH_CODE AND
        INIT_YR(TO_CHAR(FROM_DATE,'MM/YYYY'))   = INIT_YR(:P_MNYR)
        ) AND
(A.EMP_ID, A.ATTEND_DATE) NOT IN (
		SELECT EMP_ID, ADJ_DATE
        FROM HR_OFFDAY_ADJUST
        WHERE 
        COMPANY_CODE=:P_COMPANY_CODE AND
        COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE AND
        INIT_YR(TO_CHAR(ADJ_DATE,'MM/YYYY')) =  INIT_YR(:P_MNYR)
) AND
B.DEPT_GROUP = S.DEPT_GROUP  AND
B.DEPT_CODE  = S.DEPT_CODE  AND
B.DESIG_CODE = S.DESIG_CODE AND
A.COMPANY_CODE = :P_COMPANY_CODE AND
A.COMPANY_BRANCH_CODE = :P_COMPANY_BRANCH_CODE AND
S.DESIG_GROUP   NOT IN ('FW') AND
(S.DESIG_GROUP = :P_DESIG_GROUP OR :P_DESIG_GROUP IS NULL) AND
(B.DEPT_GROUP  = :P_DEPT_GROUP OR :P_DEPT_GROUP IS NULL) AND
(B.DEPT_CODE = :P_DEPT_CODE OR :P_DEPT_CODE IS NULL) AND
--(B.BLOCK_CODE = :P_BLOCK OR :P_BLOCK IS NULL) AND
(A.EMP_ID = :P_EMP OR :P_EMP IS NULL) AND
(B.EMP_STATUS IN('A') OR B.EMP_STATUS IN('I') AND 
B.EMP_INACTIVE_DT > (TO_DATE('01/'||:P_MNYR,'DD/MM/YYYY'))) AND
INIT_YR(TO_CHAR(A.ATTEND_DATE,'MM/YYYY')) = INIT_YR(:P_MNYR)    

UNION

SELECT DISTINCT A.ADJ_DATE ,TO_CHAR(A.ADJ_DATE,'DY') DD, A.EMP_ID,B.NAME, NULL,NULL, NULL,
B.BASIC_SALARY, NULL,B.JOIN_DT,B.BANK_SAL_FLAG,B.EMP_AC_NO,B.EMP_AC_DATE,B.MOBILE_BANK_SAL_FLAG,B.MOBILE_AC_NO,
B.MOBILE_AC_DATE, B.DEPT_GROUP,B.DEPT_CODE,B.DESIG_CODE,B.SALARY_TYPE,S.DESIG_GROUP ,G.DEPT_GROUP_SL
FROM HR_OFFDAY_ADJUST A, EMP B, DESIGNATION S, DEPT_GROUP G
WHERE 
(B.DEPT_GROUP = G.DEPT_GROUP_CODE) AND
A.COMPANY_CODE  =B.COMPANY_CODE AND
A.COMPANY_BRANCH_CODE =B.COMPANY_BRANCH_CODE AND
A.EMP_ID=B.EMP_ID AND
B.DEPT_GROUP = S.DEPT_GROUP  AND
B.DEPT_CODE = S.DEPT_CODE  AND
B.DESIG_CODE = S.DESIG_CODE AND
A.COMPANY_CODE = :P_COMPANY_CODE AND
A.COMPANY_BRANCH_CODE = :P_COMPANY_BRANCH_CODE AND
------S.DESIG_GROUP   NOT IN ('FW') AND
(S.DESIG_GROUP = :P_DESIG_GROUP OR :P_DESIG_GROUP IS NULL) AND
(B.DEPT_GROUP = :P_DEPT_GROUP OR :P_DEPT_GROUP IS NULL) AND
(B.DEPT_CODE = :P_DEPT_CODE OR :P_DEPT_CODE IS NULL) AND
--(B.BLOCK_CODE   = :P_BLOCK OR :P_BLOCK IS NULL) AND
(A.EMP_ID = :P_EMP OR :P_EMP IS NULL) AND
(A.EMP_ID,A.ADJ_DATE) NOT IN (
		SELECT EMP_ID,ADJ_DATE
        FROM HR_OFFDAY_ADJUST
        WHERE 
        COMPANY_CODE=:P_COMPANY_CODE AND
        COMPANY_BRANCH_CODE=:P_COMPANY_BRANCH_CODE AND
        (OFFDAY_ADJUST IS NULL AND  LUNCH_ADJUST IS NULL) OR
        (OFFDAY_ADJUST ='C' AND  LUNCH_ADJUST ='C') AND
        INIT_YR(TO_CHAR(ADJ_DATE,'MM/YYYY')) =  INIT_YR(:P_MNYR)
) AND
(B.EMP_STATUS IN('A') OR B.EMP_STATUS IN('I') AND 
B.EMP_INACTIVE_DT > (TO_DATE('01/'||:P_MNYR,'DD/MM/YYYY'))) AND
INIT_YR(TO_CHAR(A.ADJ_DATE ,'MM/YYYY')) = INIT_YR(:P_MNYR)   ) X))                                 

ORDER BY 
DEPT_GROUP_SL, DEPT_GROUP, DEPT_CODE, DESIG_CODE, JOIN_DT,
EMP_ID, ATTEND_DATE

-------------------------------------------Offday Allowance Query End ----------------------------------------------------